"""
Core sync logic: watermark management and upsert to Cloud SQL.

Column handling: Compass result JSON omits keys whose value is NULL, so row
keys are NOT a reliable description of the table (inferring the column list
from them once dropped whole columns for entire pages). The columns each
table syncs are therefore declared up front in column_map.json -- validated
against BOTH schema catalogs -- and committed alongside the DAGs. Every run
upserts exactly that column list; a key absent from a row is what Compass
means by NULL, and is written as NULL.
"""

import json
import logging
import os
from datetime import datetime, timezone

import psycopg2
import psycopg2.extras

from .compass import CompassClient
from .secrets import get_ionapi, get_cloudsql_dsn

log = logging.getLogger(__name__)

SCHEMA = 'infor'

# Columns generated by the extract query itself (SELECT aliases), not present
# in the Data Lake object schema but part of every synced table.
PIPELINE_COLUMNS = ("xxx_last_modified_datetime", "xxx_extraction_datetime")

# The validated column map, committed alongside the DAGs so every deploy
# carries it. One entry per synced table: the columns the sync may write,
# plus any source-only properties it should ignore rather than warn about.
COLUMN_MAP_PATH = os.path.join(os.path.dirname(__file__), "..", "column_map.json")

_column_map_cache = None


def get_column_map(table: str) -> tuple[dict[str, str], frozenset]:
    """Return (columns, expected_keys) for one table from the validated map.

    `columns` is {column: pg_data_type} -- exactly what the sync upserts.
    `expected_keys` additionally includes the table's known source-only
    properties, so anything outside it is genuine source schema drift.

    Loaded from column_map.json (cached per process). A missing file or table
    is a hard error: the sync must never guess its column list from row data.
    """
    global _column_map_cache
    if _column_map_cache is None:
        try:
            with open(COLUMN_MAP_PATH) as f:
                _column_map_cache = json.load(f)["tables"]
        except FileNotFoundError:
            raise RuntimeError(
                f"{COLUMN_MAP_PATH} not found -- it must be committed and "
                "deployed alongside the DAGs")
    entry = _column_map_cache.get(table)
    if entry is None:
        raise RuntimeError(
            f"table {table!r} missing from column_map.json -- add an entry "
            "for it (columns the sync may write) before syncing it")
    columns = entry["columns"]
    expected = frozenset(columns) | frozenset(entry.get("source_only", []))
    return columns, expected


STATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS _sync_state (
    table_name  TEXT PRIMARY KEY,
    last_watermark TIMESTAMPTZ,
    last_run    TIMESTAMPTZ,
    last_row_count INTEGER
);
"""


def get_pg_conn(dsn: str):
    conn = psycopg2.connect(dsn)
    conn.autocommit = False
    return conn


def get_watermark(pg_conn, table: str) -> str | None:
    with pg_conn.cursor() as cur:
        cur.execute(
            "SELECT last_watermark FROM _sync_state WHERE table_name = %s",
            (table,),
        )
        row = cur.fetchone()
        return row[0].isoformat() if row and row[0] else None


def set_watermark(pg_conn, table: str, watermark: str, row_count: int):
    with pg_conn.cursor() as cur:
        cur.execute("""
            INSERT INTO _sync_state (table_name, last_watermark, last_run, last_row_count)
            VALUES (%s, %s, now(), %s)
            ON CONFLICT (table_name) DO UPDATE
              SET last_watermark = EXCLUDED.last_watermark,
                  last_run       = EXCLUDED.last_run,
                  last_row_count = EXCLUDED.last_row_count
        """, (table, watermark, row_count))
    pg_conn.commit()


# Postgres types that need value coercion. NiFi did these conversions;
# the inherited schemas don't always match the types Compass returns.
_NUMERIC_TYPES = {"smallint", "integer", "bigint", "numeric", "real", "double precision"}
_INT_TYPES = {"smallint", "integer", "bigint"}


def _coerce(value, data_type: str):
    if data_type in _NUMERIC_TYPES:
        if isinstance(value, bool):
            return int(value)
        if value == "true":
            return 1
        if value == "false":
            return 0
    if data_type in _INT_TYPES:
        # Compass returns some integer fields as floats (e.g. 5.0) or float
        # strings ("5.0"). round() matches Postgres numeric -> int cast
        # semantics, so values that aren't exactly integral don't fail.
        if isinstance(value, float):
            return round(value)
        if isinstance(value, str):
            try:
                return round(float(value))
            except ValueError:
                pass
    return value


def upsert_rows(pg_conn, table: str, rows: list[dict], columns: dict[str, str],
                expected_keys: frozenset = frozenset(),
                unknown_keys: set | None = None):
    """Upsert one page of rows using the validated column list.

    `columns` is the fixed {column: pg_data_type} map from column_map.json;
    the SQL text is therefore identical for every page and every run. Source
    keys are matched case-insensitively (Compass returns mixed case, e.g.
    `Deleted`, `kpetRowID`; the map guarantees no case collisions). A key
    absent from a row means NULL in the Data Lake and is written as NULL --
    including on updates, so a value that changed non-NULL -> NULL propagates.

    Keys outside `expected_keys` (mapped columns + known source-only
    properties) are collected into `unknown_keys`: source schema drift that
    no Postgres column receives.
    """
    if not rows:
        return 0

    # Identifiers are always quoted: SX.e columns include reserved words
    # ("order", "full") and hyphenated names ("mfg-no") that break unquoted.
    target_cols = list(columns)
    update_clause = ", ".join(
        f'"{c}" = EXCLUDED."{c}"' for c in target_cols if c != "rowpointer")
    col_list = ", ".join(f'"{c}"' for c in target_cols)
    placeholders = ", ".join(["%s"] * len(target_cols))

    sql = f"""
        INSERT INTO {SCHEMA}.{table} ({col_list})
        VALUES ({placeholders})
        ON CONFLICT (rowpointer) DO UPDATE SET {update_clause}
    """

    def params(row):
        lowered = {k.lower(): v for k, v in row.items()}
        if unknown_keys is not None:
            unknown_keys.update(k for k in lowered if k not in expected_keys)
        if lowered.get("rowpointer") is None:
            raise ValueError(
                f"table={table}: source row has no rowpointer: "
                f"{json.dumps(row, default=str)[:500]}")
        return [_coerce(lowered.get(c), columns[c]) for c in target_cols]

    with pg_conn.cursor() as cur:
        psycopg2.extras.execute_batch(
            cur, sql, (params(row) for row in rows), page_size=500)
    pg_conn.commit()
    return len(rows)


def sync_table(table: str, gcp_project: str):
    """Full incremental sync cycle for one table.

    Secrets are fetched here at execution time, not at DAG parse time,
    to avoid hitting Secret Manager on every scheduler parse cycle.
    """
    client = CompassClient(get_ionapi(gcp_project))
    pg = get_pg_conn(get_cloudsql_dsn(gcp_project))

    try:
        current_max = client.get_max_lastmodified(table)
        if current_max is None:
            log.info("table=%s no data in Data Lake, skipping", table)
            return

        watermark = get_watermark(pg, table)

        if watermark is None:
            log.info("table=%s initial load up to %s", table, current_max)
            pages = client.fetch_initial(table, until=current_max)
        else:
            log.info("table=%s incremental %s -> %s", table, watermark, current_max)
            if watermark >= current_max:
                log.info("table=%s already up to date", table)
                return
            pages = client.fetch_incremental(table, since=watermark, until=current_max)

        columns, expected_keys = get_column_map(table)

        # Upsert page-by-page so memory stays bounded regardless of result size.
        # The watermark is only advanced after all pages succeed; a mid-load
        # failure just re-upserts the same rows on retry (idempotent).
        count = 0
        unknown_keys = set()
        for page in pages:
            count += upsert_rows(pg, table, page, columns, expected_keys, unknown_keys)
            log.info("table=%s progress: %d rows upserted", table, count)

        if unknown_keys:
            log.warning(
                "table=%s source returned %d key(s) not in column_map.json "
                "(dropped; update the map if the source schema changed): %s",
                table, len(unknown_keys), ", ".join(sorted(unknown_keys)))

        set_watermark(pg, table, current_max, count)
        log.info("table=%s upserted %d rows, watermark=%s", table, count, current_max)

    finally:
        pg.close()
